table dim_date
	lineageTag: cf6cd1fe-4210-4a82-9dbd-7b565a2715c1

	column date_key
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 3ec6cc45-11dd-48d3-ab91-0f3464bdf8bb
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: bd575f5f-60dd-498a-bdb4-ece48ab41f8d
		summarizeBy: none
		sourceColumn: full_date

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column day_number
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: fea3ce24-a872-48c4-bf0a-8f8c748c85b8
		summarizeBy: sum
		sourceColumn: day_number

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: d4bb9f88-e53f-4016-97df-a7ef93518f2f
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column week_number
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 4cfbf3ea-7d77-4fb5-a2bd-f133c616d5b8
		summarizeBy: sum
		sourceColumn: week_number

		annotation SummarizationSetBy = Automatic

	column month_number
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2f15414b-eaf1-47f3-8d99-50ddfb794edb
		summarizeBy: sum
		sourceColumn: month_number

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4754797a-f724-46ec-bc20-13da75ce989f
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column quarter_number
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 361e83ba-bd7a-4185-8173-0eb90a73fca7
		summarizeBy: sum
		sourceColumn: quarter_number

		annotation SummarizationSetBy = Automatic

	column year_number
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 80e2add6-b4bd-4bfa-b2ef-4a2bbc40b452
		summarizeBy: sum
		sourceColumn: year_number

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: f08184ea-4d28-4fd8-9566-8daa37d5a909
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 20b2ccc2-aa49-4ed5-ada1-397b828a05bf
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	hierarchy full_date_hierachy
		lineageTag: bc46d602-ca2a-4193-9db5-31341b9addec

		level year_number
			lineageTag: bac8c132-262d-4f4b-ac6f-2e702da4dbc2
			column: year_number

		level month_name
			lineageTag: b65b4fec-6f4c-4866-90d8-a614505bc8a5
			column: month_name

		level month_number
			lineageTag: a883576a-03a8-410a-bd6a-49b2edbb6b7a
			column: month_number

		level quarter_number
			lineageTag: 09747179-ccbe-40ab-a3de-25e6a39c6e03
			column: quarter_number

	partition dim_date = m
		mode: directQuery
		source =
				let
				    Source = Sql.Database("3ukzqa5oadlurln3behjhxf4ae-rzokdaunzywe7at6ssyxmwpm3a.datawarehouse.fabric.microsoft.com", "lh_insurance_dev"),
				    gold_dim_date = Source{[Schema="gold",Item="dim_date"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(gold_dim_date,{{"full_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

