table pending_payment
	lineageTag: 6e4d97d8-ba32-40b4-bfdb-adf87ec231e5

	column aging_bucket
		dataType: string
		lineageTag: 74657557-c310-4f92-8621-57e0e43bd456
		summarizeBy: none
		sourceColumn: aging_bucket

		annotation SummarizationSetBy = Automatic

	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: de5ee5c7-8eb7-4abd-825f-20ad0ba08a8b
		summarizeBy: sum
		sourceColumn: sort_order

		annotation SummarizationSetBy = Automatic

	partition pending_payment = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlDQVTBXSEmsLFbSUTJUitWJVrIAChkbwMSMwGLGhkBBM7igMVjQDCRoCRc0AQvGlBoYGKciCZsqxcYCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [aging_bucket = _t, sort_order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"aging_bucket", type text}, {"sort_order", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

