flowchart TD
  Dev["Developer (branch: feature/*)"] --> Repo["Git Repository"]
  Repo --> PR["Pull Request + Review"]
  PR --> Merge["Merge to DEV branch"]
  Merge --> Actions["GitHub Actions Pipeline"]
  Actions --> Fabric["Fabric Pipeline <br> (Notebook, Activity)"]
  Actions --> PowerBI["Power BI<br>Report<br>Semantic Model<br>Dashboard"]
  Fabric --> Workspace["Fabric Workspace"]
  PowerBI --> Workspace

