name: Update Fabric Notebook Metadata

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  update-notebooks:

    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv

      - name: Update Notebook Metadata
        env:
          DEPLOY_ENV: ${{ inputs.environment }}

          FABRIC_WORKSPACE_DEV_ID: ${{ secrets.FABRIC_WORKSPACE_DEV_ID }}
          FABRIC_LAKEHOUSE_DEV_ID: ${{ secrets.FABRIC_LAKEHOUSE_DEV_ID }}
          FABRIC_LAKEHOUSE_DEV_NAME: ${{ secrets.FABRIC_LAKEHOUSE_DEV_NAME }}

          FABRIC_WORKSPACE_PROD_ID: ${{ secrets.FABRIC_WORKSPACE_PROD_ID }}
          FABRIC_LAKEHOUSE_PROD_ID: ${{ secrets.FABRIC_LAKEHOUSE_PROD_ID }}
          FABRIC_LAKEHOUSE_PROD_NAME: ${{ secrets.FABRIC_LAKEHOUSE_PROD_NAME }}

        run: |
          python cicd/scripts/github-action/update_fabric_metadata.py